# Generated by Django 3.2.12 on 2023-08-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=30)),
                ('likes', models.IntegerField()),
                ('pub_date', models.DateTimeField()),
                ('image', models.ImageField(upload_to='img')),
            ],
        ),
    ]
