# Generated by Django 3.2.12 on 2023-08-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='desc',
            field=models.CharField(default=0, max_length=400),
        ),
    ]
